import { PluginInput, parseThresholdSeconds } from "../schema";

function escapeForDoubleQuotes(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/**
 * CPU script interprets thresholds as CPU % used.
 * Example input: "cpu > 80" -> WARNING_THRESHOLD=80
 */
export function generateCpuPluginScript(input: PluginInput): string {
  const description = input.description || "CPU check";
  const author = input.author || "Unknown";
  const version = input.version || "1.0.0";

  const timeoutSeconds = input.timeoutSeconds ?? 5;

  const warn = parseThresholdSeconds(input.warningThreshold ?? null);
  const crit = parseThresholdSeconds(input.criticalThreshold ?? null);

  const hasWarn = warn != null ? 1 : 0;
  const hasCrit = crit != null ? 1 : 0;

  const warnVal = warn ?? 0;
  const critVal = crit ?? 0;

  const descEsc = escapeForDoubleQuotes(description);

  return `#!/usr/bin/env bash

# ${descEsc}
# Author: ${escapeForDoubleQuotes(author)}
# Version: ${escapeForDoubleQuotes(version)}
#
# Nagios exit codes:
#   OK=0, WARNING=1, CRITICAL=2, UNKNOWN=3
#
# Generated by Nagios Plugin Generator (CPU)
set -u

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

TIMEOUT_SECONDS=${timeoutSeconds}
HAS_WARNING=${hasWarn}
HAS_CRITICAL=${hasCrit}
WARNING_THRESHOLD=${warnVal}
CRITICAL_THRESHOLD=${critVal}

require_bin() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "UNKNOWN - missing dependency: $1"
    exit $STATE_UNKNOWN
  }
}

require_bin top
require_bin awk
require_bin bc

print_help() {
  cat <<EOF
${descEsc}

Usage: $0

This plugin reads CPU usage from:
  top -bn1 | grep "Cpu(s)"

Thresholds (CPU % used):
  WARNING_THRESHOLD=$WARNING_THRESHOLD (enabled=$HAS_WARNING)
  CRITICAL_THRESHOLD=$CRITICAL_THRESHOLD (enabled=$HAS_CRITICAL)
EOF
}

print_version() { echo "${escapeForDoubleQuotes(version)}"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) print_help; exit $STATE_OK ;;
    -V|--version) print_version; exit $STATE_OK ;;
    *) echo "Unknown option: $1"; exit $STATE_UNKNOWN ;;
  esac
done

# We don't have a native timeout wrapper; rely on top being quick.
CPU_LINE="$(top -bn1 2>/dev/null | grep -m1 "Cpu(s)" || true)"
if [[ -z "$CPU_LINE" ]]; then
  echo "UNKNOWN - Unable to read CPU usage from top"
  exit $STATE_UNKNOWN
fi

# Extract idle %, then compute used=100-idle
IDLE="$(printf "%s" "$CPU_LINE" | awk -F',' '{for(i=1;i<=NF;i++){if($i ~ /id/){gsub(/[^0-9.]/,\"\",$i); print $i; exit}}}')"
if [[ -z "$IDLE" ]]; then
  echo "UNKNOWN - Unable to parse idle CPU from: $CPU_LINE"
  exit $STATE_UNKNOWN
fi

CPU_USED="$(echo "100 - $IDLE" | bc -l 2>/dev/null || echo "")"
if [[ -z "$CPU_USED" ]]; then
  echo "UNKNOWN - Unable to compute CPU used"
  exit $STATE_UNKNOWN
fi

if [[ "$HAS_CRITICAL" -eq 1 ]]; then
  if [[ "$(echo "$CPU_USED > $CRITICAL_THRESHOLD" | bc -l 2>/dev/null || echo 0)" -eq 1 ]]; then
    echo "CRITICAL - CPU \${CPU_USED}% used (>\${CRITICAL_THRESHOLD}%)"
    exit $STATE_CRITICAL
  fi
fi

if [[ "$HAS_WARNING" -eq 1 ]]; then
  if [[ "$(echo "$CPU_USED > $WARNING_THRESHOLD" | bc -l 2>/dev/null || echo 0)" -eq 1 ]]; then
    echo "WARNING - CPU \${CPU_USED}% used (>\${WARNING_THRESHOLD}%)"
    exit $STATE_WARNING
  fi
fi

echo "OK - CPU \${CPU_USED}% used"
exit $STATE_OK
`;
}

