import { PluginInput, parseThresholdSeconds } from "../schema";
import { resolveEffectiveTarget } from "../commandGenerator";

function escapeForDoubleQuotes(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/**
 * Disk script interprets thresholds as disk % used for the target filesystem/path.
 * Uses: df -h <path>
 */
export function generateDiskPluginScript(input: PluginInput): string {
  const description = input.description || "Disk check";
  const author = input.author || "Unknown";
  const version = input.version || "1.0.0";

  const targetPath = (resolveEffectiveTarget(input).trim() || "/").replace(/\s+/g, "");
  if (!targetPath.startsWith("/")) {
    throw new Error("Disk target must be a filesystem path like / or /var.");
  }

  const warn = parseThresholdSeconds(input.warningThreshold ?? null);
  const crit = parseThresholdSeconds(input.criticalThreshold ?? null);

  const hasWarn = warn != null ? 1 : 0;
  const hasCrit = crit != null ? 1 : 0;

  const warnVal = warn ?? 0;
  const critVal = crit ?? 0;

  const descEsc = escapeForDoubleQuotes(description);
  const pathEsc = escapeForDoubleQuotes(targetPath);

  return `#!/usr/bin/env bash

# ${descEsc}
# Author: ${escapeForDoubleQuotes(author)}
# Version: ${escapeForDoubleQuotes(version)}
#
# Nagios exit codes:
#   OK=0, WARNING=1, CRITICAL=2, UNKNOWN=3
#
# Generated by Nagios Plugin Generator (Disk)
set -u

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

TARGET_PATH="${pathEsc}"
HAS_WARNING=${hasWarn}
HAS_CRITICAL=${hasCrit}
WARNING_THRESHOLD=${warnVal}
CRITICAL_THRESHOLD=${critVal}

require_bin() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "UNKNOWN - missing dependency: $1"
    exit $STATE_UNKNOWN
  }
}

require_bin df
require_bin awk
require_bin bc

print_help() {
  cat <<EOF
${descEsc}

Usage: $0

Target path:
  $TARGET_PATH

Thresholds (Disk % used):
  WARNING_THRESHOLD=$WARNING_THRESHOLD (enabled=$HAS_WARNING)
  CRITICAL_THRESHOLD=$CRITICAL_THRESHOLD (enabled=$HAS_CRITICAL)
EOF
}

print_version() { echo "${escapeForDoubleQuotes(version)}"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) print_help; exit $STATE_OK ;;
    -V|--version) print_version; exit $STATE_OK ;;
    *) echo "Unknown option: $1"; exit $STATE_UNKNOWN ;;
  esac
done

DF_LINE="$(df -h "$TARGET_PATH" 2>/dev/null | awk 'NR==2 {print $5\" \"$3\" \"$2; exit}')"
if [[ -z "$DF_LINE" ]]; then
  echo "UNKNOWN - Unable to read disk usage for $TARGET_PATH"
  exit $STATE_UNKNOWN
fi

USE_PCT_RAW="$(printf "%s" "$DF_LINE" | awk '{print $1}')"
USED="$(printf "%s" "$DF_LINE" | awk '{print $2}')"
TOTAL="$(printf "%s" "$DF_LINE" | awk '{print $3}')"

USE_PCT="$(printf "%s" "$USE_PCT_RAW" | tr -d '%')"
if ! [[ "$USE_PCT" =~ ^[0-9]+$ ]]; then
  echo "UNKNOWN - Unable to parse disk % from: $DF_LINE"
  exit $STATE_UNKNOWN
fi

if [[ "$HAS_CRITICAL" -eq 1 ]]; then
  if [[ "$(echo "$USE_PCT > $CRITICAL_THRESHOLD" | bc -l 2>/dev/null || echo 0)" -eq 1 ]]; then
    echo "CRITICAL - Disk \${USE_PCT}% used on $TARGET_PATH (\${USED}/\${TOTAL}) (>\${CRITICAL_THRESHOLD}%)"
    exit $STATE_CRITICAL
  fi
fi

if [[ "$HAS_WARNING" -eq 1 ]]; then
  if [[ "$(echo "$USE_PCT > $WARNING_THRESHOLD" | bc -l 2>/dev/null || echo 0)" -eq 1 ]]; then
    echo "WARNING - Disk \${USE_PCT}% used on $TARGET_PATH (\${USED}/\${TOTAL}) (>\${WARNING_THRESHOLD}%)"
    exit $STATE_WARNING
  fi
fi

echo "OK - Disk \${USE_PCT}% used on $TARGET_PATH (\${USED}/\${TOTAL})"
exit $STATE_OK
`;
}

