import { PluginInput, parseThresholdSeconds } from "../schema";
import { normalizeHttpUrl } from "../httpInput";
import { inferRuleFlags, resolveEffectiveTarget } from "../commandGenerator";

function escapeForDoubleQuotes(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export function generateHttpPluginScript(input: PluginInput): string {
  const description = input.description || "HTTP check";
  const author = input.author || "Unknown";
  const version = input.version || "1.0.0";

  const rawTarget = resolveEffectiveTarget(input);
  const url = normalizeHttpUrl(rawTarget);

  const timeoutSeconds = input.timeoutSeconds ?? 5;

  const warnSec = parseThresholdSeconds(input.warningThreshold ?? null);
  const critSec = parseThresholdSeconds(input.criticalThreshold ?? null);

  const flags = inferRuleFlags(input.description || "");
  // Defaults for HTTP: if no keywords, enable both
  const enableLatency =
    flags.enableLatencyLogic || (!flags.enableLatencyLogic && !flags.enableStatusLogic);
  const enableStatus =
    flags.enableStatusLogic || (!flags.enableLatencyLogic && !flags.enableStatusLogic);

  const hasWarn = warnSec != null ? 1 : 0;
  const hasCrit = critSec != null ? 1 : 0;

  const warnVal = warnSec ?? 0;
  const critVal = critSec ?? 0;

  const urlEsc = escapeForDoubleQuotes(url);
  const descEsc = escapeForDoubleQuotes(description);

  return `#!/usr/bin/env bash

# ${descEsc}
# Author: ${escapeForDoubleQuotes(author)}
# Version: ${escapeForDoubleQuotes(version)}
#
# Nagios exit codes:
#   OK=0, WARNING=1, CRITICAL=2, UNKNOWN=3
#
# Generated by Nagios Plugin Generator (HTTP/API)
set -u

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

URL="${urlEsc}"
TIMEOUT_SECONDS=${timeoutSeconds}

ENABLE_STATUS=${enableStatus ? 1 : 0}
ENABLE_LATENCY=${enableLatency ? 1 : 0}

HAS_WARNING=${hasWarn}
HAS_CRITICAL=${hasCrit}
WARNING_THRESHOLD=${warnVal}
CRITICAL_THRESHOLD=${critVal}

require_bin() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "UNKNOWN - missing dependency: $1"
    exit $STATE_UNKNOWN
  }
}

require_bin curl
require_bin bc

print_help() {
  cat <<EOF
${descEsc}

Usage: $0

Target:
  URL=$URL

Timeout:
  --max-time $TIMEOUT_SECONDS

Curl format:
  curl -s -S -o /dev/null -w "%{http_code} %{time_total}" "$URL"

Thresholds (seconds):
  WARNING_THRESHOLD=$WARNING_THRESHOLD (enabled=$HAS_WARNING)
  CRITICAL_THRESHOLD=$CRITICAL_THRESHOLD (enabled=$HAS_CRITICAL)
EOF
}

print_version() {
  echo "${escapeForDoubleQuotes(version)}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) print_help; exit $STATE_OK ;;
    -V|--version) print_version; exit $STATE_OK ;;
    *) echo "Unknown option: $1"; exit $STATE_UNKNOWN ;;
  esac
done

# Capture HTTP_CODE and RESPONSE_TIME
CURL_OUTPUT="$(curl -s -S -o /dev/null -w "%{http_code} %{time_total}" --max-time "$TIMEOUT_SECONDS" "$URL" 2>&1)"
CURL_EXIT=$?

if [[ $CURL_EXIT -ne 0 ]]; then
  echo "CRITICAL - curl failed (exit=$CURL_EXIT): $CURL_OUTPUT"
  exit $STATE_CRITICAL
fi

read -r HTTP_CODE RESPONSE_TIME <<<"$CURL_OUTPUT"

if ! [[ "$HTTP_CODE" =~ ^[0-9]{3}$ ]]; then
  echo "UNKNOWN - Unable to parse HTTP code from: $CURL_OUTPUT"
  exit $STATE_UNKNOWN
fi

if [[ -z "$RESPONSE_TIME" ]]; then
  echo "UNKNOWN - Unable to parse response time from: $CURL_OUTPUT"
  exit $STATE_UNKNOWN
fi

# 1) CRITICAL if HTTP_CODE >= 400 (when enabled)
if [[ "$ENABLE_STATUS" -eq 1 && "$HTTP_CODE" -ge 400 ]]; then
  echo "CRITICAL - HTTP $HTTP_CODE, Response time \${RESPONSE_TIME}s"
  exit $STATE_CRITICAL
fi

# 2) CRITICAL if RESPONSE_TIME > CRITICAL_THRESHOLD (when enabled)
if [[ "$ENABLE_LATENCY" -eq 1 && "$HAS_CRITICAL" -eq 1 ]]; then
  if [[ "$(echo "$RESPONSE_TIME > $CRITICAL_THRESHOLD" | bc -l 2>/dev/null || echo 0)" -eq 1 ]]; then
    echo "CRITICAL - HTTP $HTTP_CODE, Response time \${RESPONSE_TIME}s (>\${CRITICAL_THRESHOLD}s)"
    exit $STATE_CRITICAL
  fi
fi

# 3) WARNING if RESPONSE_TIME > WARNING_THRESHOLD (when enabled)
if [[ "$ENABLE_LATENCY" -eq 1 && "$HAS_WARNING" -eq 1 ]]; then
  if [[ "$(echo "$RESPONSE_TIME > $WARNING_THRESHOLD" | bc -l 2>/dev/null || echo 0)" -eq 1 ]]; then
    echo "WARNING - HTTP $HTTP_CODE, Response time \${RESPONSE_TIME}s (>\${WARNING_THRESHOLD}s)"
    exit $STATE_WARNING
  fi
fi

echo "OK - HTTP $HTTP_CODE, Response time \${RESPONSE_TIME}s"
exit $STATE_OK
`;
}

