import { PluginInput, parseThresholdSeconds } from "../schema";

function escapeForDoubleQuotes(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/**
 * Memory script interprets thresholds as memory % used.
 * Uses: free -m
 */
export function generateMemoryPluginScript(input: PluginInput): string {
  const description = input.description || "Memory check";
  const author = input.author || "Unknown";
  const version = input.version || "1.0.0";

  const warn = parseThresholdSeconds(input.warningThreshold ?? null);
  const crit = parseThresholdSeconds(input.criticalThreshold ?? null);

  const hasWarn = warn != null ? 1 : 0;
  const hasCrit = crit != null ? 1 : 0;

  const warnVal = warn ?? 0;
  const critVal = crit ?? 0;

  const descEsc = escapeForDoubleQuotes(description);

  return `#!/usr/bin/env bash

# ${descEsc}
# Author: ${escapeForDoubleQuotes(author)}
# Version: ${escapeForDoubleQuotes(version)}
#
# Nagios exit codes:
#   OK=0, WARNING=1, CRITICAL=2, UNKNOWN=3
#
# Generated by Nagios Plugin Generator (Memory)
set -u

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

HAS_WARNING=${hasWarn}
HAS_CRITICAL=${hasCrit}
WARNING_THRESHOLD=${warnVal}
CRITICAL_THRESHOLD=${critVal}

require_bin() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "UNKNOWN - missing dependency: $1"
    exit $STATE_UNKNOWN
  }
}

require_bin free
require_bin awk
require_bin bc

print_help() {
  cat <<EOF
${descEsc}

Usage: $0

This plugin reads memory usage from:
  free -m

Thresholds (Memory % used):
  WARNING_THRESHOLD=$WARNING_THRESHOLD (enabled=$HAS_WARNING)
  CRITICAL_THRESHOLD=$CRITICAL_THRESHOLD (enabled=$HAS_CRITICAL)
EOF
}

print_version() { echo "${escapeForDoubleQuotes(version)}"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) print_help; exit $STATE_OK ;;
    -V|--version) print_version; exit $STATE_OK ;;
    *) echo "Unknown option: $1"; exit $STATE_UNKNOWN ;;
  esac
done

MEM_LINE="$(free -m 2>/dev/null | awk '/^Mem:/ {print $2\" \"$3; exit}')"
if [[ -z "$MEM_LINE" ]]; then
  echo "UNKNOWN - Unable to read memory usage from free"
  exit $STATE_UNKNOWN
fi

TOTAL_MB="$(printf "%s" "$MEM_LINE" | awk '{print $1}')"
USED_MB="$(printf "%s" "$MEM_LINE" | awk '{print $2}')"

if [[ -z "$TOTAL_MB" || -z "$USED_MB" ]]; then
  echo "UNKNOWN - Unable to parse memory values"
  exit $STATE_UNKNOWN
fi

MEM_USED_PCT="$(echo "scale=2; ($USED_MB / $TOTAL_MB) * 100" | bc -l 2>/dev/null || echo "")"
if [[ -z "$MEM_USED_PCT" ]]; then
  echo "UNKNOWN - Unable to compute memory % used"
  exit $STATE_UNKNOWN
fi

if [[ "$HAS_CRITICAL" -eq 1 ]]; then
  if [[ "$(echo "$MEM_USED_PCT > $CRITICAL_THRESHOLD" | bc -l 2>/dev/null || echo 0)" -eq 1 ]]; then
    echo "CRITICAL - Memory \${MEM_USED_PCT}% used (\${USED_MB}MB/\${TOTAL_MB}MB) (>\${CRITICAL_THRESHOLD}%)"
    exit $STATE_CRITICAL
  fi
fi

if [[ "$HAS_WARNING" -eq 1 ]]; then
  if [[ "$(echo "$MEM_USED_PCT > $WARNING_THRESHOLD" | bc -l 2>/dev/null || echo 0)" -eq 1 ]]; then
    echo "WARNING - Memory \${MEM_USED_PCT}% used (\${USED_MB}MB/\${TOTAL_MB}MB) (>\${WARNING_THRESHOLD}%)"
    exit $STATE_WARNING
  fi
fi

echo "OK - Memory \${MEM_USED_PCT}% used (\${USED_MB}MB/\${TOTAL_MB}MB)"
exit $STATE_OK
`;
}

